### ISSUE TITLE
recursive:true throws Exception

### ISSUE THREAD

**Issue by tommyTanaka** [mattbrailsford/umbraco-vorto#44]
Hi,

this code throws the following exception. If there is a value in the property, it works but without, I got the error.

```
if(Model.Content.HasVortoValue("keywords", recursive: true))
{
    keywords = Model.Content.GetVortoValue("keywords", recursive: true).ToString();
}
```

Exception:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoInnerGetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue)
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue, String fallbackCultureName)
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, Object defaultValue, String fallbackCultureName)
   bei ASP._Page_Views_MacroPartials_Metatags_cshtml.Execute()

**Comment by mattbrailsford** [comment]
What version of vorto are you using? I believe this should have been fixed in 1.5.1

**Comment by tommyTanaka** [comment]
Ok, Version 1.4 was installed. I updated to 1.5.1 and now, my Grid-Renderer throws an error:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: string enthält keine Definition für sections. bei CallSite.Target(Closure , CallSite , Object ) bei ASP._Page_Views_Partials_Grid_bootstrap3_cshtml.Execute() in c:\inetpub\wwwroot\umbHbiG\Views\Partials\Grid\Bootstrap3.cshtml:Zeile 9. bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy() bei System.Web.Mvc.WebViewPage.ExecutePageHierarchy() bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) bei Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) bei System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) bei ASP._Page_Views_MacroPartials_RenderInhaltsseite_cshtml.Execute() in c:\inetpub\wwwroot\umbHbiG\Views\MacroPartials\RenderInhaltsseite.cshtml:Zeile 8.

**Comment by tommyTanaka** [comment]
With Version : 1.5.0-alpha-000022, it works.

**Comment by tommyTanaka** [comment]
Sorry, wir 1.5.0.-alpha 26. I'm running Umbraco 7.4.1

**Comment by tommyTanaka** [comment]
But here I still get the error:
ystem.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.DoInnerGetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue)
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue[T](IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue, String fallbackCultureName)
   bei Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, Object defaultValue, String fallbackCultureName)
   bei ASP._Page_Views_MacroPartials_Metatags_cshtml.Execute() in c:\inetpub\wwwroot\umbHbiG\Views\MacroPartials\Metatags.cshtml:Zeile 15.


Happy easter, by the way and thanks for listening. :)

**Comment by mattbrailsford** [comment]
Could you try the latest nightly?
https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/artifacts

**Comment by tommyTanaka** [comment]
Fixed the problem from this post, but I get the grid-render error again.

**Comment by mattbrailsford** [comment]
Can you explain your setup a bit further? How is the grid relevant to the vorto property?

**Comment by mattbrailsford** [comment]
Also, what is happening in RenderInhaltsseite.csht at line 8?

**Comment by tommyTanaka** [comment]
It renders a Vorto Datatype of grid in a PartialView Macro with:

```
@{		
	try
	{
	if(Model.Content.HasVortoValue("Grid")){
		@Html.Partial("Grid/bootstrap3",Model.Content.GetVortoValue("Grid"))
	}
	}
	catch(Exception e)
	{
		<p>@e.ToString()</p>
	}
}
```

**Comment by mattbrailsford** [comment]
And what's the code in Bootstrap3.cshtml?

**Comment by tommyTanaka** [comment]
I setup a normal Grid and connected it to the vorto datatype. 
In Version 1.5.0 Alpha, everything works.

This is the common umbraco code:

```
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}
```

**Comment by mattbrailsford** [comment]
Ok, I know what the problem is now. We switched some code around when converting a values type to the target type, which seems to break this. Have switched it back and added a comment to ensure it doesn't get moved again in future. Try this build: https://ci.appveyor.com/project/mattbrailsford/umbraco-vorto/build/1.5.2.45/artifacts

**Comment by tommyTanaka** [comment]
Best easter egg of the day. This fixed the problem. Thank you so much again. :)
